# Generated by Django 2.2.4 on 2019-08-09 09:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=140)),
                ('published_date', models.DateTimeField(default=datetime.datetime(2019, 8, 9, 9, 13, 23, 642106, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='twitter.Tweet')),
            ],
        ),
    ]
